<a href="https://colab.research.google.com/github/semthedev/ml-course-2025/blob/main/seminar/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install jupyter-black
%load_ext jupyter_black

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 31.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.6 MB/s eta 0:00:00


## NumPy - Numerical Python
**библиотека для эффективных вычислений**

Python -- высокоуровневый, интепретируемый и динамический язык. Списки в нём -- списки указателей на объекты (которые могут иметь любой тип), и при выполнении, например, "векторных операций" (с помощью циклов или list comprehensions) интерпретатор каждый раз проверяет, применим ли тип очередного элемента.


*То, за счёт чего мы получает лаконичность кода и высокую скорость разработки, вынуждает наши программы работать медленнее.*


В numpy:
1. array должны быть одного типа, поэтому нет дополнительных вычислительных затрат на проверки.
2. Часть операций реализована на C.


Отсюда прирост в производительности на некоторых распространённых задачах -- в сотни раз.


*Неформальное правило: если вы используете numpy и если при этом в вашем коде есть циклы, скорее всего, вы делаете что-то не так.*

In [ ]:
import numpy as np

"""
Часто используемые alias'ы:
np ~ numpy
sp ~ scipy
pd ~ pandas
tf ~ tensorflow
plt ~ matplotlib.pyplot
...
"""

# numpy.ndarray -- это элементы ОДНОГО типа (в numpy их много)

array = [1, 222, 33, 5]
nparray = np.array(array)

print(array)
print(type(nparray))
print(nparray)
print(nparray.dtype)

[1, 222, 33, 5]
<class 'numpy.ndarray'>
[  1 222  33   5]
int64


In [ ]:
array = [1, 222, 33, 5.0]
nparray = np.array(array)

print(nparray)
print(nparray.dtype)

[  1. 222.  33.   5.]
float64


In [ ]:
class M(object):
    def __init__(self):
        pass


array = [1, 222, 33, "5.0", M()]
nparray = np.array(array)

print(nparray)
print(nparray.dtype)

[1 222 33 '5.0' <__main__.M object at 0x7e1ea13c7680>]
object


In [ ]:
# arange -- генерация подряд идущих чисел
# reshape -- приведение к нужной размерности
array = np.arange(40).reshape(2, 2, 10)

print(type(array))

print(array)

# размерности
print(array.ndim)

# как нумеруются оси
# строки -- axis=0
# столбцы -- axis=1
print(array.shape)
print(len(array))

print(array.astype(np.float32))

array = array.astype(np.float32)
print(array.dtype)

# также можно задавать многомерные массивы, передав в список списков [списков [списков [...]]

<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]
3
(2, 2, 10)
2
[[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]]]
float32


In [ ]:
print(np.arange(40).reshape(2, 2, 10))

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]


In [ ]:
np.arange(40).reshape(2, 2, 10).ndim

3

In [ ]:
# Другие методы создания array

# от, до, сколько частей
c = np.linspace(0, 1, 6)
d = np.linspace(0, 1, 6, endpoint=False)
print(c, d)

[0.  0.2 0.4 0.6 0.8 1. ] [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333]


In [ ]:
# на вход -- размеры массивов
e = np.zeros((2, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ee = np.zeros_like(e)
print(ee)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
f = np.ones((2, 2, 3))
print(f)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
# # на вход -- длина диагонали квадратной матрицы
g = np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
h = np.diag(np.arange(5))
i = np.diag(np.ones(3))
print(h)
print(i)

# # etc

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 1, 2])
x + y

array([4, 3, 5])

In [ ]:
x = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
x.shape

(2, 2, 3)

In [ ]:
y = np.array([[1, 2, 3], [4, 5, 6]])
y.shape

(2, 3)

In [ ]:
x + y

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
# Случайные числа из разных распределений
import random

# "зерно" для генератора случайных чисел -- для одних и тех же псвдослучайных генераций
np.random.seed(40)

# генерация сэмплов из равномерного распределения
a = np.zeros(4)
for i in range(4):
    a[i] = random.random()


a = np.random.rand(4)
print(a)

# гауссовское распределение
b = np.random.randn(50).reshape((2, 25))
print(b)

# и есть несколько других полезных на практике, google it

[0.40768703 0.05536604 0.78853488 0.28730518]
[[-1.84440103 -0.46700242  2.29249034  0.48881005  0.71026699  1.05553444
   0.0540731   0.25795342  0.58828165  0.88524424 -1.01700702 -0.13369303
  -0.4381855   0.49344349 -0.19900912 -1.27498361  0.29349415  0.10895031
   0.03172679  1.27263986  1.0714479   0.41581801  1.55067923 -0.31137892
  -1.37923991]
 [ 1.37140879  0.02771165 -0.32039958 -0.84617041 -0.43342892 -1.3370345
   0.20917217 -1.4243213  -0.55347685  0.07479864 -0.50561983  1.05240778
   0.97140041  0.07683154 -0.43500078  0.5529944   0.26671631  0.00898941
   0.64110275 -0.17770716  0.69627761 -1.1887251  -0.33169686  0.03007614
  -1.10791517]]


### Залог эффективных вычислений
#### воспринимать рекомендации по работе с numpy
*(ну или заглядывать в исходники, но это для джедаев)*

**Numpy-way strategies**
1. **Использование numpy ufuncs**
2. **Использование numpy aggregate functions**
3. **Slicing, masking, fancy indexing**
4. ***Broadcasting**

#### ufinc
A **universal function** (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

In [ ]:
# Нет ни одного шанса, что мы рассмотрим всё, что есть в numpy.
# Поэтому если есть нужда в решении какой-нибудь задачи линейной алгебры, стоит погуглить,
# наверняка в numpy/scipy есть готовое

# Сейчас учимся, "как делать правильно", а конкретные необходимые вам методы придётся погуглить

x = np.arange(6).reshape((2, 3))
print(x, x.shape)
print(x + 2)
print(x / 2)
print(x * 2)
print(x**2)

[[0 1 2]
 [3 4 5]] (2, 3)
[[2 3 4]
 [5 6 7]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  4]
 [ 9 16 25]]


In [ ]:
print(x + x)
print(x - x)

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 2  4  6]
  [ 8 10 12]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [ ]:
# NOTA BENE!
print(x * x)  # element-wise
print(x.dot(x.T))  # multiplication
print(x.T.dot(x))  # multiplication

[[ 0  1  4]
 [ 9 16 25]]
[[ 5 14]
 [14 50]]
[[ 9 12 15]
 [12 17 22]
 [15 22 29]]


In [ ]:
# а еще можно вот так
x @ x.T

array([[ 5, 14],
       [14, 50]])

In [ ]:
# а давайте проверим
x == x[0]

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
# Сюда же относятся очень эффективные
# np.log
# np.exp
# Можете не писать питоновские лямбды -- не делайте этого

print(x)
print(x[0])
print(np.array([[1, 1, 1], [1, 1, 1]]) * x[0])
x.shape, x[0].shape

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[0 1 2]
 [0 1 2]]


((2, 3), (3,))

In [ ]:
np.exp(x)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [ ]:
# let's make sure numpy's ufuncs are cool
arr = list(range(0, 60000))
%timeit [v + 5 for v in arr]

arr = np.arange(60000)
%timeit arr + 5

4.79 ms ± 795 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
26.3 µs ± 4.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# можно обычную функцию перевести вектроризовать!
import math


def my_cos(val):
    if val > 0:
        return math.cos(val)
    else:
        return 123


my_cos_vectorized = np.vectorize(my_cos)

#### II. Aggregate functions: берём коллекцию, вычисляем "агрегат"

In [ ]:
x = np.arange(60).reshape((10, 6))
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


In [ ]:
# среднее по разным измерениям
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

29.5
[27. 28. 29. 30. 31. 32.]
[ 2.5  8.5 14.5 20.5 26.5 32.5 38.5 44.5 50.5 56.5]


In [ ]:
# ст. отклонение по разным измерениям
print(np.std(x))
print(np.std(x, axis=0))
print(np.std(x, axis=1))

17.318102282486574
[17.23368794 17.23368794 17.23368794 17.23368794 17.23368794 17.23368794]
[1.70782513 1.70782513 1.70782513 1.70782513 1.70782513 1.70782513
 1.70782513 1.70782513 1.70782513 1.70782513]


In [ ]:
# а так что получится?
# print(np.std(x, axis=-1))

In [ ]:
# let's make sure numpy's aggr funcs are blazing fast
arr = list(range(0, 60000))
%timeit sum(arr)

arr = np.arange(60000)
%timeit np.sum(arr)

# убедительно? :]

735 µs ± 228 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
19.6 µs ± 3.3 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# Функции-аггрегации есть на все случаи жизни, и обычно они имеют интуитивные названия:
arr = np.arange(60000).reshape(600, 100)

# угадайте, как найти глобальный максимум максимум
mx = ...

# А построчный?
...

Ellipsis

#### III. Индексы
Если вы впервые знакомитесь с numpy - обязательно прочитайте [это](https://numpy.org/doc/stable/user/basics.indexing.html)

In [ ]:
# III. Продвинутый доступ до элементов -- каждый из них можно применять
# к ЛЮБОМУ изменению массива

arr = np.arange(120).reshape(12, 10)
print(arr.shape)
print(arr)
# 1. индексы через запятую
print(arr[0])
print(arr[0, 1])
print(arr[0][1])

(12, 10)
[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]]
[0 1 2 3 4 5 6 7 8 9]
1
1


In [ ]:
print(arr[0][1:5:2])

l = list(range(10))
l[:5]

[1 3]


[0, 1, 2, 3, 4]

In [ ]:
# индексация булевыми массивами
arr[0][[True, True, True, True, True, True, False, True, False, False]]

array([0, 1, 2, 3, 4, 5, 7])

In [ ]:
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [ ]:
arr.shape

(12, 10)

In [ ]:
# а это что за зверь?
arr[:, np.newaxis, [0, 1], np.newaxis].shape

(12, 1, 2, 1)

In [ ]:
np.newaxis is None

True

In [ ]:
arr[0][arr[0] % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
# # 2. слайсинг по любому индексу
print(arr[:2, :])

# # 3. можно передавать список индексов (как лист, так и np.ndarray)
print(arr[[0, 3], :1])
print(arr[np.array([0, 3]), :1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0]
 [30]]
[[ 0]
 [30]]


In [ ]:
# # 4. хитрый отбор элементов -- masking
x = np.random.randn(100)

# элементы больше среднего
print(x > 0.5)
print(x[x > 0.5])

[False False False False False False False  True False False  True False
  True  True False False  True  True False False False False False  True
 False False False False  True  True False  True  True  True False False
  True  True False  True False False  True False False False  True False
 False  True False  True  True  True False False  True False False  True
  True  True False  True False False False False False False  True False
 False False False False False False False False False False  True False
 False  True  True  True False False False False False False False False
 False False False False]
[0.80432571 0.92027615 1.86825697 1.76934996 0.94844044 1.5278355
 0.8872979  0.54627626 0.82000871 1.7417511  0.87603633 0.79511739
 1.76101748 1.00055791 1.9081589  0.94708268 1.01326978 1.18997822
 0.83524308 1.22609704 1.72169283 0.6397264  0.55576899 1.55630085
 1.2840827  2.4523538  1.95102122 0.59674957 0.69247125 1.20930302
 0.66539588]


In [ ]:
# всё, что выпадает за три сигмы
print(x[(x < mnstdr) & (x > mnstdl)])

%timeit x[(x < mnstdr) & (x > mnstdl)]

[-1.51702699  0.45600276 -0.86025976 -1.05905649 -0.74237576 -0.1863936
 -0.32671717  0.80432571  0.2079763  -0.03813704  0.92027615 -0.54387028
  1.86825697  1.76934996 -0.44994016 -1.33974061  0.94844044  1.5278355
 -0.25693526 -1.39488544  0.08272428 -0.26019278  0.44480736  0.8872979
 -1.3026177  -0.16682567 -1.70582163 -0.22036875  0.54627626  0.82000871
 -0.30362954  1.7417511   0.87603633  0.79511739 -0.39155736 -1.12614983
  1.76101748  1.00055791 -2.1199455   1.9081589  -1.05247805  0.0813231
  0.94708268 -0.53371674  0.01359646 -1.43838044  1.01326978 -0.38062482
  0.30563645  1.18997822  0.48149476  0.83524308  1.22609704  1.72169283
 -0.21137761 -1.21598295  0.6397264  -1.24751009  0.03137696  0.55576899
  1.55630085  1.2840827  -0.52525765  2.4523538  -1.70632707  0.45006017
 -1.04214031 -1.47674443 -0.51870141 -0.01755243  1.95102122  0.36809772
 -0.97629927  0.35430853 -0.63895086 -0.2467184  -0.51120513 -0.33014789
 -1.45017724 -0.02398285 -0.39518661  0.59674957 -1.828

In [ ]:
mn = np.mean(x)
std = 3 * np.std(x)
mnstdr = mn + std
mnstdl = mn - std

%timeit filter(lambda x: x < mnstdr or x > mnstdl, x)


# У маскинга свой небольшой язык
# Например,
# not = ~
# and = &
# or = |
# >, <, >=, <=

220 ns ± 55.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


#### IV* Broadcasting

In [ ]:
# https://numpy.org/doc/stable/user/basics.broadcasting.html - посмотрите хотя-бы картинки, будет гораздо понятнее
# часто возникает необходимость делать операции с массивами формально неподходящего размера:
np.arange(10) + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# а так -- можно?
# np.arange(10) + np.array([1, 2])

In [ ]:
x = np.arange(10).reshape(5, 2)
print(x)
y = np.array([1, 2])
print(y)
(x + y).reshape(10)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1 2]


array([ 1,  3,  3,  5,  5,  7,  7,  9,  9, 11])

In [ ]:
# А это почему так получилось?
x = np.arange(10).reshape(2, 5)
y = np.array([[1], [2]])
(x + y).reshape(10)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

---

In [ ]:
# Пусть у нас есть точка x и массив точек X. Как мне найти близжайшую к X точку в массиве?

x = np.array([111.0, 188.0])
X = np.array([[102.0, 203.0], [132.0, 193.0], [45.0, 155.0], [57.0, 173.0]])

...

Ellipsis

Более строго, правила такие:

**Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

**Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised:

### Задача 1: Попарные углы (1 балл)

Даны набор векторов. Без использования циклов в Python найдите номера двух различных векторов, угол между которыми - минимален. Максимум 3 строки, соответсвующие форматированию jupyter_black.

In [ ]:
import numpy as np

# 10 векторов в R^4
x = np.array(
    [
        [-1.05247805, 0.0813231, 0.94708268, -0.53371674],
        [0.01359646, -1.43838044, 1.01326978, -0.38062482],
        [0.30563645, 1.18997822, 0.48149476, 0.83524308],
        [1.22609704, 1.72169283, -0.21137761, -1.21598295],
        [0.6397264, -1.24751009, 0.03137696, 0.55576899],
        [1.55630085, 1.2840827, -0.52525765, 2.4523538],
        [-1.70632707, 0.45006017, -1.04214031, -1.47674443],
        [-0.51870141, -0.01755243, 1.95102122, 0.36809772],
        [-0.97629927, 0.35430853, -0.63895086, -0.2467184],
        [-0.51120513, -0.33014789, -1.45017724, -0.02398285],
    ]
)
N = np.linalg.norm(x, axis=1, keepdims=True)
S = (x @ x.T) / (N * N.T) - 2 * np.eye(x.shape[0])
i, j = np.unravel_index(np.argmax(S), S.shape)

print(i, j)

assert (i, j) == (6, 8) or (i, j) == (8, 6), "Wrong Answer"

6 8


### Задача 2: Cвертка (1 балл)
Реализуйте двумерную свертку при помощи numpy без использования циклов в python.
Максимум 4 строки,  соответсвующие форматированию jupyter_black.

![](https://upload.wikimedia.org/wikipedia/commons/1/19/2D_Convolution_Animation.gif)

